//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeavingCertificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogStudentData
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string MotherName { get; set; }
        public string MotherTounge { get; set; }
        public string Nationality { get; set; }
        public string Caste { get; set; }
        public string Religion { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string LastSchool { get; set; }
        public string Standard { get; set; }
        public string Progress { get; set; }
        public string Conduct { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public string CurrentStandard { get; set; }
        public string ReasonOfLeaving { get; set; }
        public string Remarks { get; set; }
    }
}
